language: java
sudo: false
jdk:
- openjdk8
install: true
script: "./travis-build.sh"
env:
  global:
    secure: rGCe4Jact9YXFzH952iyEqVYS8VWUM+iOtY28ZUKfNaS8PqaCikH6NOS9a+BsevMpgSOP3fT1RH8PRuydGNPoi6uKL4KHLfTmF77hFzhTnQNklSuiquLxw1acz4gO4q0j4w+4d6R02kiwpyI2W0qTsfRvbus79lkHL1DOCcWbUj4YFnoHCrGodQRkCtMk45oubirXsU7OOhMJRa4IYxbEI+Htu+of5uhJsLKE2rRU4odxHir2tifjW2gy8c2t587LrfbqTlRBYQ+cFgEfd+jzlbelKGmPlMUY+ldhZrFoqcmn9CA6JajaQfVdmI6xbj1wqJf46lijF9agArz9pvrJT1FV+BFfUP7TFErUWCxxscvdTld1UezHehgwf5gnaVIkTP3nKFwXbuWRW7RanZbpce6+mFKULSWPeVePyx0ZjWQoTkW2OVRizZnJQdGnkaIty921HBQLOq8p3MlP33mEPVroxwQ37BL/aZKjI9DLXfi8TCg0JZsJccabM35kSj/ePHufvXJW1j5mMr2aXWEtkZAoVrTaX1M5BRY44keQ86iHug5glEpHBB2pIRwGjYLWLr1hCHY9PQ5OLzcdPCSx2dRRGzJ6ApkF7KxJhnC+cuSppFhP1+LzIERfIg2oHRkuO6knXvA8TmAtSXBFUPfOx/IcRNSq1cQJaueIv6QvNM=
