language: java

jdk:
  - openjdk8

script:
  - "./travis.sh"
env:
  global:
    secure: tETIIo9enQ4/xpzA7h0iHlgX8Ny8GtqZbsYRbPmMo8keX4Pr5hX8nsPfP6U0CVrh39twzWSCWdXPlUihQ7qGCwX1MmQcni/mPsR1SeR84IRV5OxTdPPteK+OaGH5VGhyF+BEJ5+dey+UAOY+rNf/yw6z6k9PDlMSKBCZ5NqC2572P+kdHt2s/XeLLGrlboesY5gL5cxaFoly192Z+74rF4E/MGRtFJxtPksTKnqoAyxUYa9JpTe+Fwmxy4sUwhI3iEsF0xD27d7a5odojzDIgW1SXJR5ZrdCEpI3qoA8eTdeZrAGxn1/6wlfUEVDEk/6tHYp8VFLuUw8/mLtHy1qlF6E4sdnWi7fFTUYLF/glwkWkUakuvsjoDL+xX8yUsoTB6/9vR2dDpv/moNLNDvkWRYZ+uccjH1VLJHWFQ6TM2Q8sXy0vfjwggpVnmcBMxR0xAWzcsHW+4EDcKmYKccOU/gdj6eqlbRUldnK3Kv82f2TfkPaUaTytpzMHq7y2cbqbGXbgb90ntiOiPWJ6BGia0PE3U+wRwj3xmISdrOALLXNNEq35v30R2J/zD8roiik8y/2ulwtIIC+YF1JMQgAR5cVZtF2Um/4NurBd9An4ouyl4OBr1xR5b73HhzAmys9ErkaVIG1BO+R1PnrwH2fdcv9jXixBvSyWGxEE8yynSw=
